// ── Styles ────────────────────────────────────────────────────────────────────

export const s: Record<string, React.CSSProperties> = {
  page:               { padding: '1.5rem', background: 'var(--bg-page)', minHeight: 'calc(100vh - 56px)', fontFamily: "'DM Sans', sans-serif", boxSizing: 'border-box' },
  pageHeader:         { marginBottom: '1.5rem' },
  pageTitle:          { margin: 0, fontSize: 20, fontWeight: 600, color: 'var(--text-primary)', letterSpacing: '-0.01em' },
  pageSubtitle:       { margin: '4px 0 0', fontSize: 13, color: 'var(--text-secondary)' },

  entityRow:          { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: '1rem' },
  entityCard:         { display: 'flex', alignItems: 'center', gap: 14, padding: '1.1rem 1.25rem', background: 'var(--bg-card)', borderRadius: 12, cursor: 'pointer', textAlign: 'left', fontFamily: "'DM Sans', sans-serif", transition: 'box-shadow 0.15s, border 0.15s', position: 'relative' },
  entityIconWrap:     { width: 52, height: 52, borderRadius: 12, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  entityInfo:         { flex: 1 },
  entityLabel:        { fontSize: 15, fontWeight: 600, marginBottom: 3, transition: 'color 0.15s' },
  entityDesc:         { fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.4 },
  entityActiveDot:    { width: 8, height: 8, borderRadius: '50%', position: 'absolute', top: 12, right: 12 },

  selectorBar:        { display: 'flex', alignItems: 'center', gap: 16, background: 'var(--bg-card)', border: '1px solid', borderRadius: 10, padding: '0.75rem 1.25rem', marginBottom: '1rem', flexWrap: 'wrap' },
  selectorLeft:       { display: 'flex', alignItems: 'center', gap: 7, flexShrink: 0 },
  selectorLabel:      { fontSize: 13, fontWeight: 500 },
  selectorRight:      { display: 'flex', alignItems: 'center', gap: 10, flex: 1, flexWrap: 'wrap' },
  entitySelect:       { height: 34, padding: '0 10px', border: '1.5px solid', borderRadius: 7, background: 'var(--bg-input)', color: 'var(--text-primary)', fontSize: 13, fontFamily: "'DM Sans', sans-serif", outline: 'none', cursor: 'pointer', minWidth: 200 },
  chipRow:            { display: 'flex', gap: 6, flexWrap: 'wrap' },
  chip:               { width: 32, height: 32, borderRadius: '50%', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontSize: 11, fontWeight: 600, cursor: 'pointer', fontFamily: "'DM Sans', sans-serif", transition: 'all 0.15s' },

  controls:           { display: 'flex', gap: 20, marginBottom: '1.25rem', flexWrap: 'wrap', alignItems: 'center' },
  controlGroup:       { display: 'flex', alignItems: 'center', gap: 10 },
  controlLabel:       { fontSize: 12, fontWeight: 500, color: 'var(--text-secondary)', letterSpacing: '0.03em', textTransform: 'uppercase', whiteSpace: 'nowrap' },
  toggleRow:          { display: 'flex', gap: 3, background: 'var(--bg-toggle)', border: '0.5px solid var(--border)', borderRadius: 8, padding: 3 },
  toggleBtn:          { padding: '5px 13px', borderRadius: 6, fontSize: 12, fontWeight: 500, border: 'none', cursor: 'pointer', background: 'transparent', color: 'var(--text-secondary)', fontFamily: "'DM Sans', sans-serif", whiteSpace: 'nowrap' },
  toggleBtnActive:    { background: 'var(--bg-active)', color: '#1D9E75', border: '0.5px solid var(--border-input)' },
  chartTypeBtn:       { display: 'flex', alignItems: 'center', gap: 5, padding: '5px 12px', borderRadius: 6, fontSize: 12, fontWeight: 500, border: 'none', cursor: 'pointer', background: 'transparent', color: 'var(--text-secondary)', fontFamily: "'DM Sans', sans-serif" },
  chartTypeBtnActive: { background: 'var(--bg-active)', color: '#378ADD', border: '0.5px solid var(--border-input)' },
  scopeBadge:         { fontSize: 11, fontWeight: 500, padding: '3px 10px', borderRadius: 20 },
  downloadBtn:        { display: 'inline-flex', alignItems: 'center', gap: 6, padding: '7px 14px', background: '#1D9E75', color: '#fff', border: 'none', borderRadius: 8, fontSize: 12, fontWeight: 500, fontFamily: "'DM Sans', sans-serif", cursor: 'pointer', whiteSpace: 'nowrap', letterSpacing: '0.01em' },

  kpiRow:             { display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0,1fr))', gap: 12, marginBottom: '1.25rem' },
  kpiCard:            { background: 'var(--bg-card)', border: '0.5px solid var(--border)', borderRadius: 10, padding: '1rem 1.25rem' },
  kpiTop:             { display: 'flex', alignItems: 'center', gap: 6, marginBottom: 6 },
  kpiDot:             { width: 8, height: 8, borderRadius: '50%', flexShrink: 0, display: 'inline-block' },
  kpiLabel:           { fontSize: 12, color: 'var(--text-secondary)' },
  kpiVal:             { fontSize: 26, fontWeight: 600, color: 'var(--text-primary)', lineHeight: 1 },
  kpiSub:             { fontSize: 11, color: 'var(--text-tertiary)', marginTop: 4 },

  chartCard:          { background: 'var(--bg-card)', border: '0.5px solid var(--border)', borderRadius: 12, padding: '1.25rem' },
  chartHeader:        { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1.25rem' },
  chartTitle:         { fontSize: 13, fontWeight: 500, color: 'var(--text-primary)' },
  chartTypeBadge:     { fontSize: 11, fontWeight: 500, background: 'var(--bg-filter)', color: 'var(--text-secondary)', padding: '3px 10px', borderRadius: 20, border: '0.5px solid var(--border)' },
  chartWrap:          { position: 'relative', height: 320 },
  donutContainer:     { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '3rem', height: '100%' },
  donutRight:         { display: 'flex', flexDirection: 'column', gap: 10 },
  donutNote:          { margin: '0 0 8px', fontSize: 12, color: 'var(--text-secondary)' },
  donutRow:           { display: 'flex', alignItems: 'center', gap: 8, fontSize: 13 },
  donutLabel:         { flex: 1, color: 'var(--text-primary)' },
  donutVal:           { fontWeight: 600, color: 'var(--text-primary)', minWidth: 40, textAlign: 'right' },

  emptyState:         { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 12, padding: '4rem', background: 'var(--bg-card)', border: '0.5px solid var(--border)', borderRadius: 12, marginTop: 8 },
  emptyIcon:          { width: 64, height: 64, borderRadius: '50%', background: 'var(--bg-filter)', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  emptyText:          { fontSize: 13, color: 'var(--text-secondary)', margin: 0 },
};