// ── Modal styles ──────────────────────────────────────────────────────────────

export const ms: Record<string, React.CSSProperties> = {
  overlay:        { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.45)', backdropFilter: 'blur(4px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: '1rem' },
  modal:          { background: 'var(--bg-card)', border: '0.5px solid var(--border)', borderRadius: 14, width: '100%', maxWidth: 540, boxShadow: '0 20px 60px rgba(0,0,0,0.2)', fontFamily: "'DM Sans', sans-serif", overflow: 'hidden', maxHeight: '90vh', overflowY: 'auto' },
  header:         { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '1.25rem 1.5rem', borderBottom: '0.5px solid var(--border)', position: 'sticky', top: 0, background: 'var(--bg-card)', zIndex: 1 },
  headerLeft:     { display: 'flex', alignItems: 'center', gap: 12 },
  headerIcon:     { width: 36, height: 36, borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  headerTitle:    { fontSize: 14, fontWeight: 600, color: 'var(--text-primary)' },
  headerSub:      { fontSize: 12, color: 'var(--text-secondary)', marginTop: 2 },
  closeBtn:       { width: 32, height: 32, borderRadius: 8, border: '0.5px solid var(--border)', background: 'transparent', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-secondary)', flexShrink: 0 },
  body:           { padding: '1.25rem 1.5rem', display: 'flex', flexDirection: 'column', gap: '1.25rem' },
  section:        { display: 'flex', flexDirection: 'column', gap: '0.75rem' },
  sectionTitle:   { display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', letterSpacing: '0.04em', textTransform: 'uppercase' },
  filterCount:    { fontSize: 10, fontWeight: 600, background: '#E1F5EE', color: '#0F6E56', padding: '1px 6px', borderRadius: 20 },
  filterGrid2:    { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px 12px' },
  filterGrid3:    { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '8px 12px' },
  field:          { display: 'flex', flexDirection: 'column', gap: 4 },
  label:          { fontSize: 11, fontWeight: 500, color: 'var(--text-secondary)', letterSpacing: '0.03em' },
  input:          { height: 34, padding: '0 10px', border: '0.5px solid var(--border-input)', borderRadius: 7, background: 'var(--bg-input)', color: 'var(--text-primary)', fontSize: 13, fontFamily: "'DM Sans', sans-serif", outline: 'none', width: '100%', boxSizing: 'border-box' },
  select:         { height: 34, padding: '0 8px', border: '0.5px solid var(--border-input)', borderRadius: 7, background: 'var(--bg-input)', color: 'var(--text-primary)', fontSize: 13, fontFamily: "'DM Sans', sans-serif", outline: 'none', width: '100%', cursor: 'pointer' },
  formatGrid:     { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 },
  formatBtn:      { display: 'flex', alignItems: 'center', gap: 10, padding: '10px 12px', background: 'var(--bg-filter)', border: '0.5px solid var(--border)', borderRadius: 10, cursor: 'pointer', fontFamily: "'DM Sans', sans-serif", textAlign: 'left', transition: 'all 0.15s' },
  formatBtnActive:{ border: '1.5px solid var(--border)', background: 'var(--bg-card)', boxShadow: '0 2px 8px rgba(0,0,0,0.06)' },
  formatIconWrap: { width: 40, height: 40, borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, transition: 'background 0.15s' },
  formatLabel:    { fontSize: 13, fontWeight: 600, transition: 'color 0.15s' },
  formatExt:      { fontSize: 11, color: 'var(--text-tertiary)', marginTop: 2 },
  formatCheck:    { width: 18, height: 18, borderRadius: '50%', border: '1.5px solid', display: 'flex', alignItems: 'center', justifyContent: 'center', marginLeft: 'auto', flexShrink: 0, transition: 'all 0.15s' },
  filenamePreview:{ display: 'flex', alignItems: 'center', gap: 6, background: 'var(--bg-filter)', border: '0.5px solid var(--border)', borderRadius: 7, padding: '7px 10px' },
  filenameText:   { fontSize: 12, color: 'var(--text-secondary)', fontFamily: "'DM Mono', monospace" },
  footer:         { display: 'flex', justifyContent: 'flex-end', gap: 8, paddingTop: '0.5rem', borderTop: '0.5px solid var(--border)', marginTop: '0.25rem' },
  cancelBtn:      { height: 36, padding: '0 16px', border: '0.5px solid var(--border)', borderRadius: 8, background: 'transparent', color: 'var(--text-secondary)', fontSize: 13, fontFamily: "'DM Sans', sans-serif", cursor: 'pointer' },
  generateBtn:    { height: 36, padding: '0 18px', border: 'none', borderRadius: 8, background: '#1D9E75', color: '#fff', fontSize: 13, fontWeight: 500, fontFamily: "'DM Sans', sans-serif", cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: 6 },
  successBody:    { padding: '2.5rem 1.5rem', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 10, textAlign: 'center' },
  successIcon:    { width: 64, height: 64, borderRadius: '50%', background: '#E1F5EE', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 4 },
  successTitle:   { fontSize: 17, fontWeight: 600, color: 'var(--text-primary)' },
  successSub:     { fontSize: 13, color: 'var(--text-secondary)', maxWidth: 320 },
  successMeta:    { display: 'flex', gap: 6, flexWrap: 'wrap', justifyContent: 'center', marginTop: 4 },
  metaChip:       { fontSize: 11, fontWeight: 500, background: 'var(--bg-filter)', color: 'var(--text-secondary)', border: '0.5px solid var(--border)', padding: '3px 10px', borderRadius: 20, display: 'inline-flex', alignItems: 'center', gap: 4 },
  successActions: { display: 'flex', gap: 8, marginTop: 8 },
  downloadBtn:    { height: 36, padding: '0 18px', border: 'none', borderRadius: 8, background: '#1D9E75', color: '#fff', fontSize: 13, fontWeight: 500, fontFamily: "'DM Sans', sans-serif", cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: 6 },
};