// ── Page styles ───────────────────────────────────────────────────────────────

export const s: Record<string, React.CSSProperties> = {
  page:           { padding: '1.5rem', background: 'var(--bg-page)', minHeight: 'calc(100vh - 56px)', fontFamily: "'DM Sans', sans-serif", boxSizing: 'border-box' },
  topbar:         { marginBottom: '1.5rem' },
  pageTitle:      { fontSize: 18, fontWeight: 600, color: 'var(--text-primary)', lineHeight: 1.2 },
  pageSub:        { fontSize: 13, color: 'var(--text-secondary)', marginTop: 3 },
  moduleGrid:     { display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: 12, marginBottom: '1.25rem' },
  moduleCard:     { position: 'relative', display: 'flex', alignItems: 'center', gap: 14, padding: '1rem 1.1rem', background: 'var(--bg-card)', border: '0.5px solid var(--border)', borderRadius: 12, cursor: 'pointer', textAlign: 'left', fontFamily: "'DM Sans', sans-serif", transition: 'all 0.15s', overflow: 'hidden' },
  moduleCardActive:{ background: 'var(--bg-card)', boxShadow: '0 4px 16px rgba(0,0,0,0.08)' },
  moduleIconWrap: { width: 46, height: 46, borderRadius: 12, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, transition: 'all 0.15s' },
  moduleInfo:     { flex: 1, minWidth: 0 },
  moduleLabel:    { fontSize: 14, fontWeight: 600, transition: 'color 0.15s' },
  moduleDesc:     { fontSize: 11, color: 'var(--text-tertiary)', marginTop: 2, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  moduleCount:    { fontSize: 13, fontWeight: 600, padding: '3px 10px', borderRadius: 20, transition: 'all 0.15s', flexShrink: 0 },
  moduleActiveDot:{ position: 'absolute', bottom: 0, left: 0, right: 0, height: 3, borderRadius: '0 0 12px 12px' },
  emptyState:     { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 10, padding: '4rem', background: 'var(--bg-card)', border: '0.5px solid var(--border)', borderRadius: 10 },
  emptyTitle:     { fontSize: 15, fontWeight: 500, color: 'var(--text-primary)' },
  emptySub:       { fontSize: 13, color: 'var(--text-tertiary)' },
  tableCard:      { background: 'var(--bg-card)', border: '0.5px solid var(--border)', borderRadius: 10, padding: '1.25rem' },
  tableTopbar:    { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1.25rem' },
  tableIconWrap:  { width: 36, height: 36, borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', flexShrink: 0 },
  tableTitle:     { fontSize: 14, fontWeight: 600, color: 'var(--text-primary)' },
  tableSub:       { fontSize: 12, color: 'var(--text-tertiary)', marginTop: 2 },
  generateBtn:    { display: 'inline-flex', alignItems: 'center', gap: 6, padding: '8px 16px', background: '#1D9E75', color: '#fff', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 500, cursor: 'pointer', fontFamily: "'DM Sans', sans-serif" },
  table:          { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
  th:             { textAlign: 'left', padding: '6px 10px', fontSize: 11, fontWeight: 500, color: 'var(--text-secondary)', borderBottom: '0.5px solid var(--border)', letterSpacing: '0.03em', whiteSpace: 'nowrap' },
  tr:             { borderBottom: '0.5px solid var(--border)', transition: 'background 0.1s' },
  td:             { padding: '10px 10px', verticalAlign: 'middle', color: 'var(--text-primary)' },
  badge:          { display: 'inline-block', padding: '2px 9px', borderRadius: 20, fontSize: 11, fontWeight: 500 },
  prioBadge:      { display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: 12 },
  prioDot:        { width: 6, height: 6, borderRadius: '50%', display: 'inline-block' },
  statusDot:      { width: 6, height: 6, borderRadius: '50%', display: 'inline-block', flexShrink: 0 },
  avatarCircle:   { width: 30, height: 30, borderRadius: '50%', color: '#fff', fontSize: 10, fontWeight: 600, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  avatarSquare:   { width: 30, height: 30, borderRadius: 7, color: '#fff', fontSize: 10, fontWeight: 600, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
};