// ── Styles ─────────────────────────────────────────────────────────────────────

export const styles: Record<string, React.CSSProperties> = {
  wrap: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f7f6',
    padding: '2rem 1rem',
    fontFamily: "'DM Sans', sans-serif",
  },
  card: {
    background: '#ffffff',
    border: '0.5px solid #e0e0e0',
    borderRadius: 12,
    padding: '2.5rem 2rem',
    width: '100%',
    maxWidth: 380,
  },
  logo:      { display: 'flex', alignItems: 'center', gap: 10, marginBottom: '2rem' },
  logoIcon:  { width: 36, height: 36, borderRadius: 10, background: '#1D9E75', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  logoText:  { fontSize: 16, fontWeight: 500, color: '#1a1a1a' },
  logoSub:   { fontSize: 11, color: '#888', fontFamily: "'DM Mono', monospace", letterSpacing: '0.05em' },
  tag:       { display: 'inline-flex', alignItems: 'center', gap: 5, background: '#E1F5EE', color: '#0F6E56', fontSize: 11, fontWeight: 500, padding: '3px 10px', borderRadius: 20, marginBottom: '1.5rem', fontFamily: "'DM Mono', monospace" },
  dot:       { width: 6, height: 6, borderRadius: '50%', background: '#1D9E75', display: 'inline-block' },
  heading:   { fontSize: 22, fontWeight: 500, color: '#1a1a1a', marginBottom: '0.35rem' },
  subheading:{ fontSize: 14, color: '#888', marginBottom: '2rem' },
  field:     { marginBottom: '1.25rem' },
  label:     { display: 'block', fontSize: 12, fontWeight: 500, color: '#888', marginBottom: 6, letterSpacing: '0.04em', textTransform: 'uppercase' },
  input:     { width: '100%', height: 40, padding: '0 12px', border: '0.5px solid #d0d0d0', borderRadius: 8, background: '#f9f9f9', color: '#1a1a1a', fontSize: 14, fontFamily: "'DM Sans', sans-serif", outline: 'none', boxSizing: 'border-box' },
  row:       { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' },
  checkLabel:{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 13, color: '#888', cursor: 'pointer' },
  forgot:    { fontSize: 13, color: '#1D9E75', textDecoration: 'none', fontWeight: 500 },
  btn:       { width: '100%', height: 42, borderRadius: 8, background: '#1D9E75', color: 'white', fontSize: 14, fontWeight: 500, fontFamily: "'DM Sans', sans-serif", border: 'none', cursor: 'pointer', letterSpacing: '0.02em' },
  demoBox:   { marginTop: '1.5rem', background: '#f9faf9', border: '0.5px solid #e0e0e0', borderRadius: 10, padding: '1rem' },
  demoTitle: { fontSize: 11, fontWeight: 500, color: '#888', letterSpacing: '0.05em', textTransform: 'uppercase' as const, marginBottom: '0.6rem' },
  demoList:  { display: 'flex', flexDirection: 'column' as const, gap: 6 },
  demoBtn:   { display: 'flex', alignItems: 'center', gap: 8, width: '100%', padding: '7px 10px', background: '#ffffff', border: '0.5px solid #e0e0e0', borderRadius: 8, cursor: 'pointer', fontFamily: "'DM Sans', sans-serif", transition: 'border-color 0.15s', textAlign: 'left' as const },
  demoDot:   { width: 8, height: 8, borderRadius: '50%', flexShrink: 0, display: 'inline-block' },
  demoLabel: { fontSize: 13, fontWeight: 500, color: '#1a1a1a', flex: 1 },
  demoUser:  { fontSize: 11, color: '#aaa', fontFamily: "'DM Mono', monospace" },
};