// ── Modal styles ──────────────────────────────────────────────────────────────

export const ms: Record<string, React.CSSProperties> = {
  overlay:        { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.45)', backdropFilter: 'blur(4px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: '1rem' },
  modal:          { background: 'var(--bg-card)', border: '0.5px solid var(--border)', borderRadius: 14, width: '100%', maxWidth: 500, boxShadow: '0 20px 60px rgba(0,0,0,0.2)', fontFamily: "'DM Sans', sans-serif", overflow: 'hidden' },
  header:         { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '1.25rem 1.5rem', borderBottom: '0.5px solid var(--border)' },
  headerLeft:     { display: 'flex', alignItems: 'center', gap: 12 },
  headerIcon:     { width: 36, height: 36, borderRadius: 10, background: '#1D9E75', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  headerTitle:    { fontSize: 15, fontWeight: 600, color: 'var(--text-primary)' },
  headerSub:      { fontSize: 12, color: 'var(--text-secondary)', marginTop: 2 },
  closeBtn:       { width: 32, height: 32, borderRadius: 8, border: '0.5px solid var(--border)', background: 'transparent', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-secondary)' },
  body:           { padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1.1rem' },
  field:          { display: 'flex', flexDirection: 'column', gap: 6 },
  label:          { fontSize: 12, fontWeight: 500, color: 'var(--text-secondary)', letterSpacing: '0.03em', display: 'flex', alignItems: 'center', gap: 6 },
  req:            { color: '#E24B4A' },
  input:          { height: 38, padding: '0 12px', border: '0.5px solid var(--border-input)', borderRadius: 8, background: 'var(--bg-input)', color: 'var(--text-primary)', fontSize: 13, fontFamily: "'DM Sans', sans-serif", outline: 'none', width: '100%', boxSizing: 'border-box' },
  select:         { height: 38, padding: '0 10px', border: '0.5px solid var(--border-input)', borderRadius: 8, background: 'var(--bg-input)', color: 'var(--text-primary)', fontSize: 13, fontFamily: "'DM Sans', sans-serif", outline: 'none', width: '100%', cursor: 'pointer' },
  inputError:     { borderColor: '#E24B4A' },
  error:          { fontSize: 11, color: '#E24B4A' },
  levelGrid:      { display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 6 },
  levelBtn:       { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 5, padding: '8px 4px', border: '0.5px solid var(--border-input)', borderRadius: 8, background: 'var(--bg-input)', color: 'var(--text-secondary)', fontSize: 12, fontWeight: 500, cursor: 'pointer', fontFamily: "'DM Sans', sans-serif", transition: 'all 0.15s' },
  levelDot:       { width: 7, height: 7, borderRadius: '50%', display: 'inline-block', flexShrink: 0 },
  levelChip:      { display: 'inline-block', padding: '1px 7px', borderRadius: 20, fontSize: 10, fontWeight: 600, marginLeft: 4 },
  levelBadgeSmall:{ display: 'inline-block', padding: '1px 7px', borderRadius: 20, fontSize: 10, fontWeight: 500 },
  emptyParent:    { display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: 'var(--text-tertiary)', background: 'var(--bg-filter)', border: '0.5px solid var(--border)', borderRadius: 8, padding: '10px 12px' },
  preview:        { background: 'var(--bg-filter)', border: '0.5px solid var(--border-light)', borderRadius: 8, padding: '10px 14px' },
  previewLabel:   { fontSize: 10, fontWeight: 500, color: 'var(--text-tertiary)', letterSpacing: '0.05em', textTransform: 'uppercase', marginBottom: 6 },
  previewPath:    { display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  previewParent:  { fontSize: 12, color: 'var(--text-secondary)' },
  previewCurrent: { fontSize: 13, fontWeight: 600 },
  footer:         { display: 'flex', justifyContent: 'flex-end', gap: 8, paddingTop: '0.75rem', borderTop: '0.5px solid var(--border)', marginTop: '0.25rem' },
  cancelBtn:      { height: 36, padding: '0 16px', border: '0.5px solid var(--border)', borderRadius: 8, background: 'transparent', color: 'var(--text-secondary)', fontSize: 13, fontFamily: "'DM Sans', sans-serif", cursor: 'pointer' },
  saveBtn:        { height: 36, padding: '0 18px', border: 'none', borderRadius: 8, background: '#1D9E75', color: '#fff', fontSize: 13, fontWeight: 500, fontFamily: "'DM Sans', sans-serif", cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: 6 },
};