// ── Page styles ───────────────────────────────────────────────────────────────

export const s: Record<string, React.CSSProperties> = {
  page:           { padding: '1.5rem', background: 'var(--bg-page)', minHeight: 'calc(100vh - 56px)', fontFamily: "'DM Sans', sans-serif", boxSizing: 'border-box' },
  topbar:         { display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '1.5rem' },
  pageTitle:      { fontSize: 18, fontWeight: 600, color: 'var(--text-primary)', lineHeight: 1.2 },
  pageSub:        { fontSize: 13, color: 'var(--text-secondary)', marginTop: 3 },
  addBtn:         { display: 'inline-flex', alignItems: 'center', gap: 6, padding: '8px 16px', background: '#1D9E75', color: '#fff', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 500, cursor: 'pointer', fontFamily: "'DM Sans', sans-serif", flexShrink: 0 },
  card:           { background: 'var(--bg-card)', border: '0.5px solid var(--border)', borderRadius: 10, padding: '1.25rem', marginBottom: '1rem' },
  legendCard:     { background: 'var(--bg-card)', border: '0.5px solid var(--border)', borderRadius: 10, padding: '0.875rem 1.25rem', marginBottom: '1rem', display: 'flex', gap: 24, flexWrap: 'wrap', alignItems: 'center' },
  legendItem:     { display: 'flex', alignItems: 'center', gap: 6 },
  legendDot:      { width: 7, height: 7, borderRadius: '50%', display: 'inline-block', flexShrink: 0 },
  legendBadge:    { display: 'inline-block', padding: '2px 8px', borderRadius: 20, fontSize: 11, fontWeight: 500 },
  legendCount:    { fontSize: 11, color: 'var(--text-tertiary)' },
  filterGrid:     { display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: '10px 12px', alignItems: 'end' },
  filterField:    { display: 'flex', flexDirection: 'column', gap: 4 },
  filterLabel:    { fontSize: 11, fontWeight: 500, color: 'var(--text-secondary)', letterSpacing: '0.04em', textTransform: 'uppercase' },
  inputWrap:      { position: 'relative' },
  inputIcon:      { position: 'absolute', left: 10, top: '50%', transform: 'translateY(-50%)', color: 'var(--text-tertiary)', pointerEvents: 'none' },
  inputWithIcon:  { height: 34, padding: '0 10px 0 32px', border: '0.5px solid var(--border-input)', borderRadius: 7, background: 'var(--bg-input)', color: 'var(--text-primary)', fontSize: 13, fontFamily: "'DM Sans', sans-serif", outline: 'none', width: '100%', boxSizing: 'border-box' },
  clearBtn:       { display: 'inline-flex', alignItems: 'center', gap: 5, fontSize: 12, color: 'var(--text-secondary)', background: 'transparent', border: '0.5px solid var(--border)', borderRadius: 6, padding: '0 10px', height: 34, cursor: 'pointer', fontFamily: "'DM Sans', sans-serif" },
  tableHeader:    { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1rem' },
  tableTitle:     { fontSize: 13, fontWeight: 500, color: 'var(--text-primary)' },
  countBadge:     { fontSize: 11, fontWeight: 500, background: 'var(--bg-filter)', color: 'var(--text-secondary)', padding: '2px 8px', borderRadius: 20, border: '0.5px solid var(--border)' },
  table:          { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
  th:             { textAlign: 'left', padding: '6px 10px', fontSize: 11, fontWeight: 500, color: 'var(--text-secondary)', borderBottom: '0.5px solid var(--border)', letterSpacing: '0.03em', whiteSpace: 'nowrap' },
  tr:             { borderBottom: '0.5px solid var(--border)', transition: 'background 0.1s' },
  td:             { padding: '10px 10px', verticalAlign: 'middle' },
  levelBadge:     { display: 'inline-block', padding: '2px 10px', borderRadius: 20, fontSize: 11, fontWeight: 500 },
  levelDotInline:   { width: 7, height: 7, borderRadius: '50%', display: 'inline-block', flexShrink: 0 },
  actionBtnDanger:  { fontSize: 12, fontWeight: 500, padding: '5px 12px', borderRadius: 6, border: 'none', cursor: 'pointer', fontFamily: "'DM Sans', sans-serif", background: '#FCEBEB', color: '#A32D2D' },
  actionBtnSuccess: { fontSize: 12, fontWeight: 500, padding: '5px 12px', borderRadius: 6, border: 'none', cursor: 'pointer', fontFamily: "'DM Sans', sans-serif", background: '#E1F5EE', color: '#0F6E56' },
};