export const s: Record<string, React.CSSProperties> = {
  nav: {
    background: 'var(--bg-card)',
    borderBottom: '0.5px solid var(--border)',
    fontFamily: "'DM Sans', sans-serif",
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  inner: {
    maxWidth: 1280,
    margin: '0 auto',
    padding: '0 1.5rem',
    height: 56,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 24,
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    textDecoration: 'none',
    flexShrink: 0,
  },
  logoIcon: {
    width: 30,
    height: 30,
    borderRadius: 8,
    background: '#1D9E75',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandText: {
    fontSize: 15,
    fontWeight: 600,
    color: 'var(--text-primary)',
    letterSpacing: '-0.01em',
  },
  navList: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    listStyle: 'none',
    margin: 0,
    padding: 0,
    flex: 1,
    justifyContent: 'center',
  },
  navLink: {
    display: 'block',
    padding: '5px 12px',
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--text-link)',
    textDecoration: 'none',
    borderRadius: 6,
    transition: 'all 0.15s',
  },
  navLinkActive: {
    color: '#1D9E75',
    background: '#E1F5EE',
  },
  themeBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 34,
    height: 34,
    borderRadius: 8,
    border: '0.5px solid var(--border)',
    background: 'transparent',
    cursor: 'pointer',
    transition: 'background 0.15s',
    flexShrink: 0,
  },
  userArea: {
    position: 'relative',
    flexShrink: 0,
  },
  avatarBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    background: 'transparent',
    border: '0.5px solid var(--border)',
    borderRadius: 8,
    padding: '5px 10px',
    cursor: 'pointer',
    fontFamily: "'DM Sans', sans-serif",
  },
  avatar: {
    width: 26,
    height: 26,
    borderRadius: '50%',
    background: '#1D9E75',
    color: '#fff',
    fontSize: 10,
    fontWeight: 600,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userName: {
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--text-primary)',
    maxWidth: 120,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  dropdown: {
    position: 'absolute',
    top: 'calc(100% + 8px)',
    right: 0,
    background: 'var(--bg-card)',
    border: '0.5px solid var(--border)',
    borderRadius: 10,
    boxShadow: '0 8px 24px rgba(0,0,0,0.12)',
    minWidth: 200,
    zIndex: 200,
    overflow: 'hidden',
  },
  dropdownHeader: {
    padding: '12px 14px',
  },
  dropdownName: {
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--text-primary)',
  },
  dropdownEmail: {
    fontSize: 12,
    color: 'var(--text-secondary)',
    marginTop: 2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  dropdownDivider: {
    height: '0.5px',
    background: 'var(--border)',
  },
  dropdownList: {
    listStyle: 'none',
    margin: 0,
    padding: '4px 0',
  },
  dropdownItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 14px',
    fontSize: 13,
    color: 'var(--text-primary)',
    textDecoration: 'none',
    transition: 'background 0.1s',
    background: 'transparent',
    fontFamily: "'DM Sans', sans-serif",
    fontWeight: 400,
  },
};