// ── Styles ────────────────────────────────────────────────────────────────────

export const s: Record<string, React.CSSProperties> = {
  overlay:          { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.35)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 500, padding: '1rem', backdropFilter: 'blur(2px)' },
  modal:            { background: '#fff', borderRadius: 14, width: '100%', maxWidth: 740, maxHeight: '90vh', display: 'flex', flexDirection: 'column', boxShadow: '0 24px 60px rgba(0,0,0,0.15)', fontFamily: "'DM Sans', sans-serif", overflow: 'hidden' },
  header:           { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '1.1rem 1.5rem', borderBottom: '0.5px solid #e8e8e8', flexShrink: 0 },
  headerLeft:       { display: 'flex', alignItems: 'center', gap: 10 },
  headerIcon:       { width: 34, height: 34, borderRadius: 9, background: '#1D9E75', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  headerTitle:      { fontSize: 15, fontWeight: 600, color: '#1a1a1a' },
  headerSub:        { fontSize: 12, color: '#888', marginTop: 1 },
  closeBtn:         { background: 'transparent', border: 'none', cursor: 'pointer', color: '#888', display: 'flex', alignItems: 'center', padding: 4, borderRadius: 6 },
  body:             { display: 'flex', flexDirection: 'column', flex: 1, overflow: 'hidden' },
  scrollArea:       { flex: 1, overflowY: 'auto', padding: '1.25rem 1.5rem', display: 'flex', flexDirection: 'column', gap: '1.5rem' },
  section:          { display: 'flex', flexDirection: 'column', gap: 12 },
  sectionTitle:     { fontSize: 12, fontWeight: 600, color: '#1a1a1a', textTransform: 'uppercase', letterSpacing: '0.06em' },
  sectionSub:       { fontSize: 11, color: '#aaa', marginTop: -8 },
  grid1:            { display: 'flex', flexDirection: 'column', gap: 12 },
  grid2:            { display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0,1fr))', gap: '10px 16px' },
  field:            { display: 'flex', flexDirection: 'column', gap: 5 },
  label:            { fontSize: 11, fontWeight: 500, color: '#666', letterSpacing: '0.04em', textTransform: 'uppercase' },
  req:              { color: '#E24B4A' },
  input:            { height: 36, padding: '0 11px', border: '0.5px solid #d8dad8', borderRadius: 7, background: '#fafafa', color: '#1a1a1a', fontSize: 13, fontFamily: "'DM Sans', sans-serif", outline: 'none', boxSizing: 'border-box', width: '100%' },
  textarea:         { padding: '9px 11px', border: '0.5px solid #d8dad8', borderRadius: 7, background: '#fafafa', color: '#1a1a1a', fontSize: 13, fontFamily: "'DM Sans', sans-serif", outline: 'none', resize: 'vertical', width: '100%', height: '300px', boxSizing: 'border-box', lineHeight: 1.5 },
  select:           { height: 36, padding: '0 8px', border: '0.5px solid #d8dad8', borderRadius: 7, background: '#fafafa', color: '#1a1a1a', fontSize: 13, fontFamily: "'DM Sans', sans-serif", outline: 'none', width: '100%', cursor: 'pointer', boxSizing: 'border-box' },
  dropzone:         { border: '1.5px dashed #d4d6d4', borderRadius: 10, padding: '2rem 1rem', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 6, cursor: 'pointer', transition: 'all 0.15s', background: '#fafafa' },
  dropzoneDragging: { borderColor: '#1D9E75', background: '#f0faf6' },
  dropzoneIcon:     { marginBottom: 4 },
  dropzoneText:     { fontSize: 13, color: '#555', textAlign: 'center' },
  dropzoneHint:     { fontSize: 11, color: '#aaa' },
  fileList:         { display: 'flex', flexDirection: 'column', gap: 6, marginTop: 4 },
  fileItem:         { display: 'flex', alignItems: 'center', gap: 10, padding: '7px 10px', background: '#f9faf9', border: '0.5px solid #e8e8e8', borderRadius: 8 },
  fileItemError:    { background: '#FFF5F5', borderColor: '#F5C0C0' },
  fileThumb:        { width: 36, height: 36, objectFit: 'cover', borderRadius: 5, flexShrink: 0 },
  fileIcon:         { width: 36, height: 36, borderRadius: 5, background: '#f0f2f1', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  fileMeta:         { flex: 1, overflow: 'hidden' },
  fileName:         { fontSize: 12, fontWeight: 500, color: '#1a1a1a', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  fileSize:         { fontSize: 11, color: '#aaa', marginTop: 1 },
  fileError:        { fontSize: 11, color: '#A32D2D', marginTop: 1 },
  fileRemove:       { background: 'transparent', border: 'none', cursor: 'pointer', color: '#aaa', display: 'flex', alignItems: 'center', padding: 2, flexShrink: 0 },
  footer:           { display: 'flex', justifyContent: 'flex-end', gap: 8, padding: '1rem 1.5rem', borderTop: '0.5px solid #e8e8e8', flexShrink: 0 },
  cancelBtn:        { height: 36, padding: '0 18px', borderRadius: 8, border: '0.5px solid #d8dad8', background: '#fff', color: '#555', fontSize: 13, fontWeight: 500, cursor: 'pointer', fontFamily: "'DM Sans', sans-serif" },
  submitBtn:        { height: 36, padding: '0 20px', borderRadius: 8, border: 'none', background: '#1D9E75', color: '#fff', fontSize: 13, fontWeight: 500, cursor: 'pointer', fontFamily: "'DM Sans', sans-serif", display: 'inline-flex', alignItems: 'center', gap: 7 },
};